plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation(platform('org.junit:junit-bom:6.0.2'))
    testImplementation('org.junit.jupiter:junit-jupiter')
    testRuntimeOnly('org.junit.platform:junit-platform-launcher')

    testImplementation('org.mockito:mockito-junit-jupiter:5.21.0')
    testImplementation('org.assertj:assertj-core:3.27.7')
}

test {
    useJUnitPlatform()
}

jar {
    manifest {
        attributes["Main-Class"] = "duke.DukeNukem"
    }
}

tasks.register("run", JavaExec) {
    mainClass = 'duke.DukeNukem'
    classpath = sourceSets.main.runtimeClasspath
}

tasks.register("packageMac", Exec) {
    dependsOn 'build'

    commandLine 'jpackage',
            '--type', 'dmg',
            '--input', 'build/libs',
            '--dest', 'build/distributions',
            '--name', 'Duke Nukem',
            '--icon', 'src/main/resources/icon.icns',
            '--main-class', 'duke.DukeNukem',
            '--main-jar', 'duke-nukem.jar',
            '--app-version', '1.0.0',
            '--mac-package-identifier', 'nl.rsuurd.duke-nukem',
            '--mac-package-name', 'Duke Nukem'
}
